name: Build BrickController iOS 

on:
  # push:
  #   branches:
  #     - default
  #     - 'release/**'
  #   paths:
  #     - '.github/**/*ios.yml'
  #     - '*.props'
  #     - '*.slnx'
  #     - 'BrickController2/BrickController2/**'
  #     - 'BrickController2/BrickController2.iOS/**'
  # pull_request:
  #   branches:    
  #     - default
  #     - 'release/**'
  #   paths:
  #     - '.github/**/*ios.yml'
  #     - '*.props'
  #     - '*.slnx'
  #     - 'BrickController2/BrickController2/**'
  #     - 'BrickController2/BrickController2.iOS/**'
  # release:
  #   types:
  #     - published
  
  workflow_dispatch:

permissions:
  contents: read

env:
  XCODE_VERSION: '26.6'
  TARGET_FRAMEWORK: 'net10.0-ios'
  TARGET_RUNTIME: 'ios-arm64'
  IOS_TRIM_MODE: ${{ (github.event_name == 'release' && github.event.action == 'published') && 'Full' || 'None' }}
  APPLE_CERTIFICATE_BASE64: ${{ secrets.APPLE_CERTIFICATE_BASE64 }}
  APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
  BUILD_PROVISIONING_PROFILE_BASE64: ${{ secrets.BUILD_PROVISIONING_PROFILE_BASE64 }}
  KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
  APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
  APPLE_BUNDLE_ID: ${{ vars.APPLE_BUNDLE_ID || 'com.scn.BrickController2' }}

jobs:
  build-ios:
    runs-on: macos-26
    name: BrickController iOS Build

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Install MAUI workload
      run: dotnet workload install maui ios

    - name: Set XCode Version
      if: runner.os == 'macOS'
      shell: bash
      run: |
        sudo xcode-select -s "/Applications/Xcode_${{ env.XCODE_VERSION }}.app"
        echo "MD_APPLE_SDK_ROOT=/Applications/Xcode_${{ env.XCODE_VERSION }}.app" >> $GITHUB_ENV

    - name: Verify Xcode version
      run: xcodebuild -version

    - name: Get App Version from Build Properties
      shell: bash
      run: echo "APP_VERSION=$(sed -n 's|.*<ApplicationDisplayVersion>\(.*\)</ApplicationDisplayVersion>.*|\1|p' Directory.Build.props)" >> $GITHUB_ENV

    - name: Find Current Release Info
      if: github.event_name == 'release' && github.event.action == 'published'
      id: get_release
      uses: octokit/request-action@v3.x
      with:
        route: GET /repos/${{ github.repository }}/releases/tags/${{ github.event.release.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Import Code-Signing Certificates
      uses: Apple-Actions/import-codesign-certs@v7
      with:
        p12-file-base64: ${{ secrets.APPLE_CERTIFICATE_BASE64 }}
        p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        
    - name: List Keychain Certificates
      run: security find-identity -v -p codesigning

    - name: Import provisioning profile
      if: env.BUILD_PROVISIONING_PROFILE_BASE64 != ''
      run: |
        mkdir -p "$RUNNER_TEMP/profiles"
        echo "$BUILD_PROVISIONING_PROFILE_BASE64" | base64 --decode > "$RUNNER_TEMP/profiles/profile.mobileprovision"
        mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
        cp "$RUNNER_TEMP/profiles/profile.mobileprovision" "$HOME/Library/MobileDevice/Provisioning Profiles/"
        
    - name: Replace CFBundleIdentifier in Info.plist
      shell: bash
      run: |
        PLIST="BrickController2/BrickController2.iOS/Info.plist"

        echo "Info.plist:"
        grep -A1 "<key>CFBundleIdentifier</key>" "$PLIST"

        BUNDLE_ID="${{ env.APPLE_BUNDLE_ID }}"

        echo "Setting CFBundleIdentifier to: $BUNDLE_ID"

        # Ersetze den Wert innerhalb des <string>...</string> nach dem CFBundleIdentifier-Key
        sed -i '' -e "/<key>CFBundleIdentifier<\/key>/{n;s|<string>.*</string>|<string>${BUNDLE_ID}</string>|;}" "$PLIST"

        echo "Updated Info.plist:"
        grep -A1 "<key>CFBundleIdentifier</key>" "$PLIST"

        # echo "Full Info.plist:"
        # cat "$PLIST"

    - name: Replace ApplicationId in csproj
      shell: bash
      run: |
        CSPROJ="BrickController2/BrickController2.iOS/BrickController2.iOS.csproj"

        echo "ApplicationId:"
        grep "<ApplicationId>" "$CSPROJ"

        BUNDLE_ID="${{ env.APPLE_BUNDLE_ID }}"

        echo "Setting ApplicationId to: $BUNDLE_ID"

        # Ersetze den Wert innerhalb des <ApplicationId>...</ApplicationId>
        sed -i '' -e "s|<ApplicationId>.*</ApplicationId>|<ApplicationId>${BUNDLE_ID}</ApplicationId>|" "$CSPROJ"

        echo "Updated ApplicationId:"
        grep "<ApplicationId>" "$CSPROJ"

        # echo "Full Info.plist:"
        # cat "$CSPROJ"

    - name: Restore Dependencies
      run: dotnet restore BrickController2/BrickController2.iOS/BrickController2.iOS.csproj
      
    - name: Build MAUI iOS
      run: |
        PROFILE_PATH=$(ls "$HOME/Library/MobileDevice/Provisioning Profiles"/*.mobileprovision | head -n1)
        if [ -z "$PROFILE_PATH" ]; then
          echo "No .mobileprovision found"
          exit 1
        fi
        echo "Found profile: $PROFILE_PATH"

        PROFILE_UUID=$(security cms -D -i "$PROFILE_PATH" 2>/dev/null | grep -A 1 "<key>UUID</key>" | grep "<string>" | sed 's/.*<string>\(.*\)<\/string>.*/\1/')
        echo "Using PROFILE_UUID=$PROFILE_UUID"
        
        if [ -z "$PROFILE_UUID" ]; then
          echo "ERROR: Failed to extract UUID from provisioning profile"
          exit 1
        fi
        
        dotnet publish BrickController2/BrickController2.iOS/BrickController2.iOS.csproj \
        --no-restore \
        -c Release \
        -f ${{ env.TARGET_FRAMEWORK }} \
        -r ${{ env.TARGET_RUNTIME }} \
        -p:ApplicationVersion="${{ github.run_number }}" \
        -p:ArchiveOnBuild=true \
        -p:CodesignKey="Apple Development" \
        -p:CodesignProvision="$RUNNER_TEMP/profiles/profile.mobileprovision" \
        -p:CodesignEntitlements="Entitlements.plist" \
        -p:EnableAssemblyILStripping=false

    - name: Analyse IPA
      run: |
        unzip -q BrickController2/BrickController2.iOS/bin/Release/${{ env.TARGET_FRAMEWORK }}/${{ env.TARGET_RUNTIME }}/publish/BrickController2.iOS.ipa -d ipa_unpacked

        echo "=== ENTITLEMENTS ==="
        codesign -d --entitlements :- ipa_unpacked/Payload/BrickController2.iOS.app || true

        echo "=== PROVISIONING PROFILE ==="
        security cms -D -i ipa_unpacked/Payload/BrickController2.iOS.app/embedded.mobileprovision || true

        echo "=== INFO.PLIST ==="
        plutil -p ipa_unpacked/Payload/BrickController2.iOS.app/Info.plist || true

    - name: List build output
      run: ls -R BrickController2/BrickController2.iOS/bin/Release/${{ env.TARGET_FRAMEWORK }}/${{ env.TARGET_RUNTIME }}/publish/

    - name: Upload IOS Artifact
      uses: actions/upload-artifact@v7
      with:
        name: brickcontroller-ios-ci-build
        path: BrickController2/BrickController2.iOS/bin/Release/${{ env.TARGET_FRAMEWORK }}/${{ env.TARGET_RUNTIME }}/publish/BrickController2.iOS.ipa

    - name: Upload Artifact to Release
      if: github.event_name == 'release' && github.event.action == 'published'
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ fromJson(steps.get_release.outputs.data).upload_url }}
        asset_path: BrickController2/BrickController2.iOS/bin/Release/${{ env.TARGET_FRAMEWORK }}/${{ env.TARGET_RUNTIME }}/publish/BrickController2.iOS.ipa
        asset_name: BrickController_${{env.APP_VERSION}}.ipa
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.CI_RELEASE_ASSETS_PAT }}
